version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: 
          command: |
            docker login -u admin -p $DOCKER_PASS docker.5f59de2e2ef742c4b229.eastus.aksapp.io
            docker build docker.5f59de2e2ef742c4b229.eastus.aksapp.io/frontend:$CIRCLE_SHA1 frontend
            docker push docker.5f59de2e2ef742c4b229.eastus.aksapp.io/frontend:$CIRCLE_SHA1