jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
        environment:
          DOCKER_OPTS='--insecure-registry docker.5f59de2e2ef742c4b229.eastus.aksapp.io'
#       auth:
#         username: admin
#         password: $DOCKER_PASS
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build docker image
          command: |
            docker build -t docker.5f59de2e2ef742c4b229.eastus.aksapp.io/frontend:$CIRCLE_SHA1 frontend
      - deploy:
          name: Push to nexus
          command: |
            docker login -u admin -p admin123 docker.5f59de2e2ef742c4b229.eastus.aksapp.io
            docker push docker.5f59de2e2ef742c4b229.eastus.aksapp.io/frontend:$CIRCLE_SHA1

